// Code generated by ogen, DO NOT EDIT.

package bawards

// AwardsListParams is parameters of AwardsList operation.
type AwardsListParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по ID традиции.
	TraditionID OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по ID инструмента.
	InstrumentID OptInt32 `json:",omitempty,omitzero"`
	// Порядок сортировки.
	OrderBy OptAwardsListOrderBy `json:",omitempty,omitzero"`
	// Включить в ответ свойство `applications`.
	WithApplications OptBool `json:",omitempty,omitzero"`
}

// ChallengeV2ReadParams is parameters of ChallengeV2Read operation.
type ChallengeV2ReadParams struct {
	ChallengeID int32
}

// ChallengesListParams is parameters of ChallengesList operation.
type ChallengesListParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ChallengesV2ListParams is parameters of ChallengesV2List operation.
type ChallengesV2ListParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	After OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ComplexChallengeGoalCreateParams is parameters of ComplexChallengeGoalCreate operation.
type ComplexChallengeGoalCreateParams struct {
	ComplexchID int32
}

// ComplexChallengeGoalDeleteParams is parameters of ComplexChallengeGoalDelete operation.
type ComplexChallengeGoalDeleteParams struct {
	GoalID int32
}

// ComplexChallengeGoalReadParams is parameters of ComplexChallengeGoalRead operation.
type ComplexChallengeGoalReadParams struct {
	GoalID int32
}

// ComplexChallengeGoalUpdateParams is parameters of ComplexChallengeGoalUpdate operation.
type ComplexChallengeGoalUpdateParams struct {
	GoalID int32
}

// ComplexChallengeGoalsListParams is parameters of ComplexChallengeGoalsList operation.
type ComplexChallengeGoalsListParams struct {
	ComplexchID int32
}

// ComplexChallengePublicParams is parameters of ComplexChallengePublic operation.
type ComplexChallengePublicParams struct {
	ComplexchID int32
	// Устанавливаемое значение свойства `public`.
	Value bool
}

// ComplexChallengeReadParams is parameters of ComplexChallengeRead operation.
type ComplexChallengeReadParams struct {
	// Вернуть объекты со свойством `goals`.
	// Доступно только при наличии административных прав.
	WithGoals   OptBool `json:",omitempty,omitzero"`
	ComplexchID int32
}

// ComplexChallengeUpdateParams is parameters of ComplexChallengeUpdate operation.
type ComplexChallengeUpdateParams struct {
	ComplexchID int32
}

// ComplexChallengeValidateParams is parameters of ComplexChallengeValidate operation.
type ComplexChallengeValidateParams struct {
	ComplexchID int32
}

// ComplexChallengesListParams is parameters of ComplexChallengesList operation.
type ComplexChallengesListParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	After OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтр по статусу опубликованности.
	Public OptBool `json:",omitempty,omitzero"`
}

// ComplexChallengesResultsListParams is parameters of ComplexChallengesResultsList operation.
type ComplexChallengesResultsListParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	After OptInt64 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по ID пользователя Таланта.
	UserID OptInt32 `json:",omitempty,omitzero"`
	// Порядок сортировки результатов.
	// Недоступно при использовании параметра `after`.
	OrderBy OptComplexChallengesResultsListOrderBy `json:",omitempty,omitzero"`
}

// InstrumentReadParams is parameters of InstrumentRead operation.
type InstrumentReadParams struct {
	// Идентификатор инструмента в адресе.
	InstrumentID int32
}

// InstrumentUpdateParams is parameters of InstrumentUpdate operation.
type InstrumentUpdateParams struct {
	// Идентификатор инструмента в адресе.
	InstrumentID int32
}

// InstrumentsListParams is parameters of InstrumentsList operation.
type InstrumentsListParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	After OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по признаку активности объектов выборки.
	// По умолчанию возвращаются только активные.
	IsActive OptIsActive `json:",omitempty,omitzero"`
	// Идентификаторы инструментов.
	ID []int32 `json:",omitempty"`
	// Фильтрация по ID традиций.
	TID []int32 `json:",omitempty"`
	// Фильтрация по ID компетенций.
	CID []int32 `json:",omitempty"`
	// Фильтрация по названию инструмента.
	Name OptString `json:",omitempty,omitzero"`
	// Очереднось выдачи.
	OrderBy OptInstrumentsListOrderBy `json:",omitempty,omitzero"`
}

// PassedChallengesListParams is parameters of PassedChallengesList operation.
type PassedChallengesListParams struct {
	// Испытания пройденные игроками, объединенными
	// пользователем, привязанным к указанному игроку.
	// При отсутствии привязанного пользователя,
	// возвращаются испытания указанного игрока.
	PlayerID OptUUID `json:",omitempty,omitzero"`
	// Испытания пройденные игроками указанного
	// пользователя.
	TalentID OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// PassedChallengesV2ListParams is parameters of PassedChallengesV2List operation.
type PassedChallengesV2ListParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	After OptInt64 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по ID испытания.
	ChallengeID OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по ID пользователя Таланта.
	UserID OptInt32 `json:",omitempty,omitzero"`
	// Порядок сортировки результатов.
	OrderBy OptPassedChallengesV2ListOrderBy `json:",omitempty,omitzero"`
}

// TraditionInstrumentsListParams is parameters of TraditionInstrumentsList operation.
type TraditionInstrumentsListParams struct {
	// Идентификатор традиции в адресе.
	TraditionID int32
}

// TraditionReadParams is parameters of TraditionRead operation.
type TraditionReadParams struct {
	// Идентификатор традиции в адресе.
	TraditionID int32
}

// TraditionUpdateParams is parameters of TraditionUpdate operation.
type TraditionUpdateParams struct {
	// Идентификатор традиции в адресе.
	TraditionID int32
}

// TraditionsListParams is parameters of TraditionsList operation.
type TraditionsListParams struct {
	// Фильтрация по названию традиции.
	Name OptString `json:",omitempty,omitzero"`
	// Фильтрация по признаку активности объектов выборки.
	// По умолчанию возвращаются только активные.
	IsActive OptIsActive `json:",omitempty,omitzero"`
}

// UserAwardDisplayedParams is parameters of UserAwardDisplayed operation.
type UserAwardDisplayedParams struct {
	AwardID int32
}

// UserAwardsListParams is parameters of UserAwardsList operation.
type UserAwardsListParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// UserProgressListParams is parameters of UserProgressList operation.
type UserProgressListParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Прогресс только по традициям.
	TraditionsOnly OptBool `json:",omitempty,omitzero"`
	// Прогресс по инструментам традиции.
	TraditionInstruments OptInt32 `json:",omitempty,omitzero"`
	// Прогресс по определенным традициям.
	TraditionIds []int32 `json:",omitempty"`
	// Прогресс по определенным инструментам.
	InstrumentIds []int32 `json:",omitempty"`
	// Порядок сортировки.
	OrderBy OptUserProgressListOrderBy `json:",omitempty,omitzero"`
}
