// Code generated by ogen, DO NOT EDIT.
package bawards

type ChallengeV2ReadRes interface {
	challengeV2ReadRes()
}

type ComplexChallengeCreateRes interface {
	complexChallengeCreateRes()
}

type ComplexChallengeGoalCreateRes interface {
	complexChallengeGoalCreateRes()
}

type ComplexChallengeGoalDeleteRes interface {
	complexChallengeGoalDeleteRes()
}

type ComplexChallengeGoalReadRes interface {
	complexChallengeGoalReadRes()
}

type ComplexChallengeGoalUpdateRes interface {
	complexChallengeGoalUpdateRes()
}

type ComplexChallengeGoalsListRes interface {
	complexChallengeGoalsListRes()
}

type ComplexChallengePublicRes interface {
	complexChallengePublicRes()
}

type ComplexChallengeReadRes interface {
	complexChallengeReadRes()
}

type ComplexChallengeUpdateRes interface {
	complexChallengeUpdateRes()
}

type ComplexChallengeValidateRes interface {
	complexChallengeValidateRes()
}

type ComplexChallengesResultsListRes interface {
	complexChallengesResultsListRes()
}

type FormulaParseRes interface {
	formulaParseRes()
}

type InstrumentCreateRes interface {
	instrumentCreateRes()
}

type InstrumentReadRes interface {
	instrumentReadRes()
}

type InstrumentUpdateRes interface {
	instrumentUpdateRes()
}

type PassedChallengesListRes interface {
	passedChallengesListRes()
}

type TraditionCreateRes interface {
	traditionCreateRes()
}

type TraditionReadRes interface {
	traditionReadRes()
}

type TraditionUpdateRes interface {
	traditionUpdateRes()
}
