// Code generated by ogen, DO NOT EDIT.

package bawards

// OperationName is the ogen operation name
type OperationName = string

const (
	AwardsListOperation                   OperationName = "AwardsList"
	ChallengeV2ReadOperation              OperationName = "ChallengeV2Read"
	ChallengesListOperation               OperationName = "ChallengesList"
	ChallengesV2ListOperation             OperationName = "ChallengesV2List"
	ComplexChallengeCreateOperation       OperationName = "ComplexChallengeCreate"
	ComplexChallengeGoalCreateOperation   OperationName = "ComplexChallengeGoalCreate"
	ComplexChallengeGoalDeleteOperation   OperationName = "ComplexChallengeGoalDelete"
	ComplexChallengeGoalReadOperation     OperationName = "ComplexChallengeGoalRead"
	ComplexChallengeGoalUpdateOperation   OperationName = "ComplexChallengeGoalUpdate"
	ComplexChallengeGoalsListOperation    OperationName = "ComplexChallengeGoalsList"
	ComplexChallengePublicOperation       OperationName = "ComplexChallengePublic"
	ComplexChallengeReadOperation         OperationName = "ComplexChallengeRead"
	ComplexChallengeUpdateOperation       OperationName = "ComplexChallengeUpdate"
	ComplexChallengeValidateOperation     OperationName = "ComplexChallengeValidate"
	ComplexChallengesListOperation        OperationName = "ComplexChallengesList"
	ComplexChallengesResultsListOperation OperationName = "ComplexChallengesResultsList"
	FormulaParseOperation                 OperationName = "FormulaParse"
	InstrumentCreateOperation             OperationName = "InstrumentCreate"
	InstrumentReadOperation               OperationName = "InstrumentRead"
	InstrumentUpdateOperation             OperationName = "InstrumentUpdate"
	InstrumentsListOperation              OperationName = "InstrumentsList"
	PassedChallengesListOperation         OperationName = "PassedChallengesList"
	PassedChallengesV2ListOperation       OperationName = "PassedChallengesV2List"
	TraditionCreateOperation              OperationName = "TraditionCreate"
	TraditionInstrumentsListOperation     OperationName = "TraditionInstrumentsList"
	TraditionReadOperation                OperationName = "TraditionRead"
	TraditionUpdateOperation              OperationName = "TraditionUpdate"
	TraditionsListOperation               OperationName = "TraditionsList"
	UserAwardDisplayedOperation           OperationName = "UserAwardDisplayed"
	UserAwardsListOperation               OperationName = "UserAwardsList"
	UserProgressListOperation             OperationName = "UserProgressList"
)
