// Code generated by ogen, DO NOT EDIT.
package beract

type ActivitiesCreateRes interface {
	activitiesCreateRes()
}

type ActivitiesScoresByTraditionsRes interface {
	activitiesScoresByTraditionsRes()
}

type ActivitiesScoresRes interface {
	activitiesScoresRes()
}

type ArtefactSetUploadedRes interface {
	artefactSetUploadedRes()
}

type ArtefactUploadURLRes interface {
	artefactUploadURLRes()
}

type ArtefactsCreateRes interface {
	artefactsCreateRes()
}
