// Code generated by ogen, DO NOT EDIT.
package beract

type ActivitiesCreateRes interface {
	activitiesCreateRes()
}

type ActivitiesMetricsListRes interface {
	activitiesMetricsListRes()
}

type ActivitiesScoresByTraditionsRes interface {
	activitiesScoresByTraditionsRes()
}

type ActivitiesScoresRes interface {
	activitiesScoresRes()
}

type ActivityReadRes interface {
	activityReadRes()
}

type ArtefactSetUploadedRes interface {
	artefactSetUploadedRes()
}

type ArtefactUploadURLRes interface {
	artefactUploadURLRes()
}

type ArtefactsCreateRes interface {
	artefactsCreateRes()
}

type ContextIDsListRes interface {
	contextIDsListRes()
}

type ContextTraditionIDRes interface {
	contextTraditionIDRes()
}

type ContextsImportReq interface {
	contextsImportReq()
}

type ContextsImportRes interface {
	contextsImportRes()
}

type ContextsListRes interface {
	contextsListRes()
}
