// Code generated by ogen, DO NOT EDIT.

package beridp

import (
	"github.com/google/uuid"
)

// ApplicationsListParams is parameters of ApplicationsList operation.
type ApplicationsListParams struct {
	Offset OptInt32
	Limit  OptInt32
	// Фильтрация по публичности приложений.
	// - true - только опубликованные
	// - false - только не опубликованные
	// - all - все.
	IsPublic OptApplicationsListIsPublic
	// Порядок сортировки результатов.
	OrderBy OptApplicationsListOrderBy
}

// PlayerGetParams is parameters of PlayerGet operation.
type PlayerGetParams struct {
	// PlayerID игрока.
	PlayerID PlayerID
	// Включить в ответ `talent_id`.
	GetTalentID OptBool
	// Включить в ответ `player_ids`.
	GetPlayerIds OptBool
}

// TalentOAuthCompleteParams is parameters of TalentOAuthComplete operation.
type TalentOAuthCompleteParams struct {
	Code  string
	State uuid.UUID
}
